# This workflow is used to create a (pre-)release build of the OpenList frontend.
#
# This will:
#
# - Update the `package.json` version to the specified version (when triggered
#   by `workflow_dispatch`), commit the changes and tag it.
# - Upload the release assets to GitHub.
# - Publish the package to npm.
#
# # Usage
#
# This workflow can be triggered by:
#
# - Pushing a tag that matches the pattern `v[0-9]+.[0-9]+.[0-9]+*` (semver format).
# - Manually via the GitHub Actions UI with a version input.
#
# To create (pre-)release builds, we recommend that you use the `workflow_dispatch`.

name: Release Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: |
          Target version (e.g., 1.0.0), will create a tag named 'v<version>' and update package.json version
        required: true
        type: string

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Validate and trim semver
        id: semver
        uses: matt-usurp/validate-semver@v2
        with:
          version: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.version || github.ref_name }}

      - name: Check if version is pre-release
        id: check_pre_release
        run: |
          if [[ -z "${{ steps.semver.outputs.prerelease }}" && -z "${{ steps.semver.outputs.build }}" ]]; then
            echo "is_pre_release=false" >> $GITHUB_OUTPUT
          else
            echo "is_pre_release=true" >> $GITHUB_OUTPUT
          fi

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          registry-url: "https://registry.npmjs.org"

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Update package.json and commit
        if: github.event_name == 'workflow_dispatch'
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          # 获取当前版本
          CURRENT_VERSION=$(jq -r '.version' package.json)
          NEW_VERSION="${{ steps.semver.outputs.version }}"

          echo "Current version: $CURRENT_VERSION"
          echo "New version: $NEW_VERSION"

          # 检查版本是否需要更新
          if [ "$CURRENT_VERSION" != "$NEW_VERSION" ]; then
            echo "Updating version from $CURRENT_VERSION to $NEW_VERSION"
            jq --arg version "$NEW_VERSION" '.version = $version' package.json > package.json.tmp && mv package.json.tmp package.json
            git add package.json
            git commit -m "chore: release v$NEW_VERSION" --no-verify
            git push
          else
            echo "Version is already $NEW_VERSION, no need to update package.json"
          fi

          # 检查标签是否已存在
          if ! git rev-parse "v$NEW_VERSION" >/dev/null 2>&1; then
            # 标签不存在，创建新标签
            echo "Creating tag v$NEW_VERSION"
            git tag "v$NEW_VERSION" -m "Release v$NEW_VERSION"
          else
            echo "Tag v$NEW_VERSION already exists"
          fi

          # 确保将标签推送到远程仓库
          echo "Pushing tag v$NEW_VERSION to remote repository"
          git push origin "v$NEW_VERSION"

      - name: Get current tag
        id: get_current_tag
        run: |
          # Remove existing tag `rolling`, since `rolling` should always point to the latest commit
          # This is necessary to avoid conflicts with the changelog generation
          git tag -d rolling 2>/dev/null || true

          # First try to get tag from current repo
          LOCAL_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")

          if [ -n "$LOCAL_TAG" ]; then
            # Use local tag if available
            CURRENT_TAG=$LOCAL_TAG
          else
            # Fetch latest tag from GitHub API if no local tag
            CURRENT_TAG=$(curl -s https://api.github.com/repos/OpenListTeam/OpenList-Frontend/tags | jq -r ".[0].name" || echo "v0.0.0")
            echo "Using latest tag from GitHub: $CURRENT_TAG"
          fi

          echo "current_tag=$CURRENT_TAG" >> $GITHUB_OUTPUT

          # Temporarily remove all pre-release tags (tags containing '-' / '+')
          # This prevents them from interfering with changelog generation
          PRE_RELEASE_TAGS=$(git tag -l | grep -E "(-|\+)" || true)
          if [ -n "$PRE_RELEASE_TAGS" ]; then
            echo "Temporarily removing pre-release tags: $PRE_RELEASE_TAGS"
            echo "$PRE_RELEASE_TAGS" | xargs -r git tag -d
          fi

          # Add back the current tag if is a pre-release
          # Should not add `-f`, as it will overwrite the existing tag
          if [[ "${{ steps.check_pre_release.outputs.is_pre_release }}" == "true" ]]; then
            git tag -s "$CURRENT_TAG" -m "Release $CURRENT_TAG"
          fi

      - name: Generate changelog
        id: generate_changelog
        run: |
          npx changelogithub --output ${{ github.workspace }}-CHANGELOG.txt || echo "" > ${{ github.workspace }}-CHANGELOG.txt

      - name: Build Release
        run: |
          chmod +x build.sh
          ./build.sh --release --compress
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

      - name: Upload Release Assets
        run: |
          # 使用用户指定的版本号
          VERSION="${{ steps.semver.outputs.version }}"
          RELEASE_TAG="v$VERSION"

          echo "Creating GitHub release for tag: $RELEASE_TAG"

          # 创建 GitHub Release
          gh release create "$RELEASE_TAG" \
            --title "Release $RELEASE_TAG" \
            --notes-file "${{ github.workspace }}-CHANGELOG.txt" \
            --prerelease=${{ steps.check_pre_release.outputs.is_pre_release }} \
            dist/openlist-frontend-dist-v*.tar.gz dist/i18n.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write
