name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    name: Build
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          registry-url: "https://registry.npmjs.org"

      - uses: pnpm/action-setup@v2.2.2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
          persist-credentials: false
          fetch-depth: 0
          submodules: recursive

      - name: Build
        run: |
          pnpm install
          pnpm i18n
          pnpm build
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

      - name: Compress dist
        run: |
          mkdir compress
          tar -czvf compress/dist.tar.gz dist/*
          zip -r compress/dist.zip dist/*

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: alist-web
          path: compress
